### ISSUE TITLE
这是一个不容易发现但8.0之后一直存在的bug

### ISSUE THREAD

**Issue by corecall** [foxyproxy/browser-extension#167] opened 2024-12-15 01:53 UTC
I have two accounts on a SOCK5 proxy, the same IP address, the same port, but the username is different, I can't choose which one to use, because the plugin always forces the last option to be checked

**Comment by erosman** [comment] 2024-12-16 06:39
Duplicate of #168

**Closed by erosman** 2024-12-16 06:39 UTC
Labels: duplicate
