### ISSUE TITLE
after update I can't use no proxy mode

### ISSUE THREAD

**Issue by alighafoori** [foxyproxy/browser-extension#59] opened 2023-12-09 12:49 UTC
when my foxyproxy was updated, in direct mode it use system proxy and I don't want use system proxy. I want firefox just use direct access like old times foxyproxy wasn't updated is there any way to rollback old version. this version is sucks

**Comment by erosman** [comment] 2023-12-09 13:21
> is there any way to rollback old version

If it is on Firefox, you can install the previous version and disable updates.

**Comment by f45tb00t** [comment] 2023-12-09 13:27
Hello,

I'm also facing issues with the new version. All configured proxies are gone. I am not really open to reconfigure everything again. 

Could you please fix this with a new releases? I did not find that much about this big changes anywhere? Can you clarify please with this happened? 

Last but not least: Thank you very much for providing FoxyProxy to us :)

@alighafoori: I would not be so demanding to such a great project. It's free of charge and you can use any other software you like. Just stay friendly, as the devs do not owe us anything!

**Comment by erosman** [comment] 2023-12-09 13:50
@f45tb00t Please note https://github.com/foxyproxy/browser-extension/issues/53#issuecomment-1848282804

**Comment by f45tb00t** [comment] 2023-12-09 13:58
> @f45tb00t Please note [#53 (comment)](https://github.com/foxyproxy/browser-extension/issues/53#issuecomment-1848282804)

Thanks erosman.

**Comment by MehradN** [comment] 2023-12-11 08:35
I have the same problem too, the latest version of foxy proxy forces the system proxy to you even in the Disabled and the DIRECT settings. So you either have to disable the system proxy or the foxy proxy extension. I hope this issue gets fixed in the next update.

**Comment by erosman** [comment] 2023-12-11 10:15
The default setting of [proxy.settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings) is "system".

> This may take any one of the following values: "none", "autoDetect", "system", "manual", "autoConfig". Defaults to "system".

I will see if it is possible to work out an alternative method.

**Comment by erosman** [comment] 2023-12-12 10:51
I have updated the code and it should fix the issue.

- Go to **Firefox Settings -> Network Settings -> Connection Settings**
- Select the preferred option
- As long as a PAC proxy is not set, the setting should remain

If you set a PAC proxy, after changing it, the setting defaults back to "system", so the process has to be repeated.

You can test the beta on the repo and let me know if it is fixed.

**Comment by erosman** [comment] 2023-12-15 09:39
Has anyone tested v8.7 to see if the issue is fixed?

**Comment by MehradN** [comment] 2023-12-19 17:09
> Has anyone tested v8.7 to see if the issue is fixed?

Yes, I can confirm the problem is fixed on v8.7

**Closed** 2023-12-19 19:06 UTC
Labels: done ✓
